version: '3'
services:
  chk-mysql:
    container_name: chk-mysql
    image: mysql:8.0.28
    ports:
      - "33306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 8f55ea2b0cd4@
      MYSQL_DATABASE: chk
      MYSQL_USER: chk
      MYSQL_PASSWORD: a87fc4993@
    volumes:
      - ./chk-db.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - chk-net
  chk-redis:
    container_name: chk-redis
    image: redis:6.2
    ports:
      - "60001:6379"
    networks:
      - chk-net
  chk:
    container_name: chk
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - chk-mysql
      - chk-redis
    volumes:
      - ./:/go/src/project
    networks:
      - chk-net
networks:
  chk-net:
    driver: bridge